CREATE TABLE brands (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `name` VARCHAR(50) NOT NULL ,
    `debt` INT NULL ,
    PRIMARY KEY (`id`)

);

CREATE TABLE products (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `category` VARCHAR(50) NOT NULL ,
    `brand_id` INT UNSIGNED NOT NULL ,
    `name` VARCHAR(50) NOT NULL ,
    `cost` INT UNSIGNED NOT NULL ,
    `sell` INT UNSIGNED NOT NULL ,
    PRIMARY KEY (`id`),
    INDEX (`brand_id`),
    FOREIGN KEY (`brand_id`) REFERENCES brand(id) 
);


CREATE TABLE sales_products (
    `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ,
    `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `sold_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ,
    `product_id` INT UNSIGNED NOT NULL ,
    `amount` INT UNSIGNED NOT NULL ,
    `cost` INT UNSIGNED NOT NULL ,
    `sell` INT UNSIGNED NOT NULL ,
    PRIMARY KEY (`id`),
    INDEX (`product_id`),
    FOREIGN KEY (`product_id`) REFERENCES products(id)
);
